name: StylizedRegions
version: '${project.version}'
main: me.blueslime.stylizedregions.StylizedRegions
api-version: 1.13
softdepend:
  - PlaceholderAPI
authors: [ JustJustin ]
description: Simple Region Plugin
